config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'posts#index'
  get 'tags/:tag', to: 'searchs#tagindex', as: :tag
  get 'searchs/tagindex' => 'searchs#tagindex'

  devise_scope :user do
    get 'sign_in' => 'users/sessions#new'
    get 'sign_out' => 'users/sessions#destroy'
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
    get '/users/:id', to: 'users#show', as: 'user'
    put 'users/follow/:user_id' => 'users#follow'
    put 'users/unfollow/:user_id' => 'users#unfollow'
    get 'users/follow_list/:user_id' => 'users#follow_list'
    get 'users/follower_list/:user_id' => 'users#follower_list'
  end

  resources :posts, only: %i[new create index show destroy] do
    resources :photos, only: %i[create]
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :searchs, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true, length: { maximum: 100 }
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    update_attribute(:blocked, true)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :caption, presence: true, length: { maximum: 100 }
  has_one_attached :avatar
  has_many_attached :images
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  acts_as_taggable

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :name, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :searchs

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  validates :name, presence: true, length: { maximum: 50 }
  validates :username, presence: true, length: { maximum: 50 } 
  validates :password, presence: true, length: { maximum: 50 }

  has_one_attached :avatar

  acts_as_followable
  acts_as_follower

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def self.guest
    find_or_create_by(email: 'guest@example.com') do |user|
      user.password = 'password'
    end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(name: data['name'], email: data['email'], password: Devise.friendly_token[0, 20])
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name username])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name text])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name text])
  end

  def set_search
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = 'コメントに失敗しました'
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = 'コメントの削除に失敗しました'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :comment)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    respond_to :js if @like.save
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    respond_to :js if @like.destroy
  end

  private

  def like_params
    params.permit(:post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show destroy]

  def new
    @post = Post.new
    @user = User.find_by(id: params[:user_id])
  end

  def create
    @post = Post.new(post_params)
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    if @post.save
      flash[:notice] = '投稿が保存されました'
      redirect_to root_path
    else
      flash[:alert] = '投稿に失敗しました'
      redirect_to root_path
    end
  end

  def index
    @posts = Post.all.order('created_at DESC')
    @posts = Post.tagged_with(params[:tag_name].to_s) if params[:tag_name]
  end

  def show; end

  def destroy
    if @post.user == current_user
      flash[:notice] = '投稿が削除されました' if @post.destroy
    else
      flash[:alert] = '投稿の削除に失敗しました'
    end
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:caption, :tag_list, :youtube_url, :address, images: []).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
    @posts = Post.includes(:user).where(posts: { user_id: params[:id] }).order('created_at DESC')
  end

  def follow
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    redirect_to user_path(@user)
  end

  def unfollow
    @user = User.find(params[:user_id])
    current_user.stop_following(@user)
    redirect_to user_path(@user)
  end

  def follow_list
    @user = User.find(params[:user_id])
  end

  def follower_list
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?

    gravatar_id = Digest::MD5.hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "partial/comment_list", { post: @post } %>');
$('#comment-form-post-<%= @post.id.to_s %> #comment_comment').val("");

app/views/comments/destroy.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "partial/comment_list", { post: @post } %>');

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいね", post_like_path(@post.id, @like), method: :DELETE, remote: true, class: "loved hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "partial/like_text", { likes: @post.likes } %>');

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいねを取り消す", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "partial/like_text", { likes: @post.likes } %>');

app/views/posts/index.html.erb
<% unless user_signed_in? %>  
  <div class="col-md-12 col-md-8 col-md-2 mx-auto">
    <div class="topcard">
      <div class="card-wrap">
        <div class="top-image">                        
          <div class="text-center my-auto">
            <h1 class="mb-1 top-h1">we will be traveler!</h1>
            <h2 class="mb-1 top-h2">〜あなたの旅行アルバムを共有しよう〜</h2>
          </div>
        </div>
        <div class="content-section-heading">
          <div class="row">
            <div class="col-md-4 mb-5 mb-lg-0 text-center">
              <span class="service-icon rounded-circle mx-auto mb-3">
                <i class="far fa-images icon-1" aria-hidden="true"></i>
              </span>
              <h4>
                <strong>つぶやき・写真投稿機能</strong>
              </h4>
              <p class="text-faded text-left mb-0">
                旅行中に感じた思いや旅行で撮った写真を投稿することができます。youtube動画の投稿も可能です。投稿したユーザーにのみ、編集・削除が可能です。
              </p>
            </div>
            <div class="col-md-4 mb-5 mb-lg-0 text-center">
              <span class="service-icon rounded-circle mx-auto mb-3">
                <i class="fas fa-user-tag icon-2" aria-hidden="true"></i>
              </span>
              <h4>
                <strong>ユーザー・タグごとの<br>投稿表示が可能</strong>
              </h4>
              <p class="text-faded text-left mb-0">
                ユーザーの検索はもちろん、登録タグからの絞り込んだ投稿を表示することができます。
              </p>
            </div>
            <div class="col-md-4 mb-5 mb-lg-0 text-center">
              <span class="service-icon rounded-circle mx-auto mb-3">
                <i class="fa fa-comments-o icon-3" aria-hidden="true"></i>
              </span>
              <h4>
                <strong>ユーザー同士で共有</strong>
              </h4>
              <p class="text-faded text-left mb-0">
                投稿された口コミにはいいね！やコメントをすることができ、フォローを通じてユーザーと繋がることができます。
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card start-card">
      <div class="form-wrap">
        <div class="form-group text-center">
          <h2 class="mx-auto top-h22">さあ、始めましょう！！</h2>
        </div>
        <br>
        <div　class="top-btn">
          <div class="top-signin text-center">
            <p class="signin-comment">アカウントを持っている方はこちら</p>
            <%= link_to "サインイン", sign_in_path, class: "btn btn-primary btn-lg" %>
          </div>
          <div class="top-signup text-center">
            <p class="signin-comment">アカウントを持っていない方はこちら</p>
            <%= link_to "サインアップ", new_user_registration_path, class: "btn btn-success btn-lg" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>


<% if user_signed_in? %>
  <% @posts.each do |post| %>
    <div class="col-md-12 col-md-8 col-md-2 mx-auto">
      <div class="card-wrap">
        <div class="card">
          <div class="card-header align-items-center d-flex flex-row">
            <%= link_to user_path(post.user), class: "no-text-decoration" do %>
              <%= image_tag(post.user.avatar.variant(resize:'50x50').processed) if post.user.avatar.attached? %>
            <% end %>
            <%= link_to user_path(post.user), class: "post-user-name black-color no-text-decoration", title: post.user.name do %>
              <strong><%= post.user.name %></strong>
            <% end %>
            <% if post.user_id == current_user.id %>
              <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon"></div>
              <% end %>
            <% end %>
          </div>
          <%= link_to(post_path(post)) do %>
            <div class="row">
              <% if post.images.count > 1 %>
                <% post.images.each do |image|%>
                  <div class="col-md-6 card-img">              
                    <%= image_tag image, class: "card-img-top" %>
                  </div>
                <% end %>
              <% else %>
                <% post.images.each do |image|%>
                  <div class="col-md-12 card-img">              
                    <%= image_tag image, class: "card-img-top" %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <% if post.youtube_url.present? %>
              <div class="youtube-movie">
                <div class="youtube-movie-content">
                  <iframe width="640" height="390" src="https://www.youtube.com/embed/<%= post.youtube_url %>" allowfullscreen></iframe>
                </div>
              </div>
            <% end %>
          
            <div class="card-body">
              <div class="card-caption m-2">
                <strong>
                  <%= post.caption %>
                </strong>
                <div class="light-color post-time no-text-decoration">
                  <span><%= time_ago_in_words(post.created_at).upcase + "前" %></span>
                </div>
              </div>
            </div>
          <% end %>
          <div class="card-body">
            <div class="card-tag m-2">
              <div>
                <tbody>
                  <% post.tag_list.each do |posttag| %>
                    <tr>
                      <%= link_to posttag, posts_path(post, tag_name: posttag), class: "label label-primary tag-design" %>
                    </tr>
                  <% end %>
                </tbody>
              </div>
            </div>
            <div class="row parts">
              <% if post.user_id != current_user.id %>
                <div id="like-icon-post-<%= post.id.to_s %>">
                  <% if post.liked_by(current_user).present? %>
                    <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
                  <% else %>
                    <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div id="like-text-post-<%= post.id.to_s %>">
              <%= render "partial/like_text", { likes: post.likes } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0 profile-new-image">
              <%= image_tag(current_user.avatar.variant(resize:'60x60').processed) if current_user.avatar.attached? %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :caption, class: "form-control", placeholder: "共有したいことを書いてね！", required: true %>
            </div>
          </div>
          <div class="mb-3">
            <div class="col pl-0">
              <%= f.label :tag_list, "ハッシュタグ (複数タグは半角スペースを空ける)" %>
              <%= f.text_field :tag_list, value: @post.tag_list.join(','), "data-role" => "tagsinput", class: "form-control" %>
            </div>
            <div class="uploader">
              <p>画像アップロード</p>
            </div>
            <%= f.file_field :images, :multiple => true %>
            <div class="uploader">
              <p>youtube動画アップロード</p>
            </div>
            <%= f.text_field :youtube_url, class: "form-control", placeholder: "youtube動画のurlを入れる" %>
            <div class="uploader">
              <p>観光地名</p>
            </div>
            <%= f.text_field :address, class: "form-control", placeholder: "住所" %>
          </div>
          <div class="text-center push-btn">
            <%= f.submit "投稿する", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <div class="row">
          <% if @post.images.count > 1 %>
            <% @post.images.each do |image|%>
              <div class="col-md-6 card-img">
                <%= image_tag image, class: "card-img-top" %>
              </div>
            <% end %>
          <% else %>
            <% @post.images.each do |image|%>
              <div class="col-md-12 card-img">
                <%= image_tag image, class: "card-img-top" %>
              </div>
            <% end %>
          <% end %>
        </div>
        <% if @post.youtube_url.present? %>
          <div class="youtube-movie">
            <div class="youtube-movie-content">
              <iframe width="640" height="390" src="https://www.youtube.com/embed/<%= @post.youtube_url %>" allowfullscreen></iframe>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= image_tag(@post.user.avatar.variant(resize:'50x50').processed) if @post.user.avatar.attached? %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>
            <% if @post.user_id == current_user.id %>
              <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon"></div>
              <% end %>
            <% end %>
          </div>
          <div class="card-caption m-2">
            <strong>
              <%= @post.caption %>
            </strong>
            <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
          </div>
          <div>
            <tbody>
              <% @post.tag_list.each do |post| %>
                <tr>
                  <span class="label label-primary tag-design"><%= post %></span>
                </tr>
              <% end %>
            </tbody>
          </div>
        </div>
        <% if @post.user_id != current_user.id %>
          <div class="row parts">
            <div id="like-icon-post-<%= @post.id.to_s %>">
              <% if @post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
            </div>
          </div>
          <div id="like-text-post-<%= @post.id.to_s %>">
            <%= render "partial/like_text", { likes: @post.likes } %>
          </div>
          <hr>
          <div class="comment-post-id">
            <div class="m-2">
              <div id="comment-post-<%= @post.id.to_s %>">
                <%= render 'partial/comment_list', post: @post %>
              </div>
            </div>
          </div>
          <div class="row parts" id="comment-form-post-<%= @post.id.to_s %>">
            <%= form_with model: [@post, Comment.new],  class: "w-100", remote: true do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :post_id, value: @post.id %>
              <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off, required: true %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div id='map'></div>
</div>

<style type="text/css">
#map{
  height: 400px;
}
</style>

<script type="text/javascript">
  function initMap() {
    var test ={lat: <%= @post.latitude %>, lng: <%= @post.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '観光地の名前：<%= @post.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });
     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>