config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'posts#index'
  get 'tags/:tag', to: 'searchs#tagindex', as: :tag
  get 'searchs/tagindex' => 'searchs#tagindex'

  devise_scope :user do
    get 'sign_in' => 'users/sessions#new'
    get 'sign_out' => 'users/sessions#destroy'
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
    get '/users/:id', to: 'users#show', as: 'user'
    put 'users/follow/:user_id' => 'users#follow'
    put 'users/unfollow/:user_id' => 'users#unfollow'
    get 'users/follow_list/:user_id' => 'users#follow_list'
    get 'users/follower_list/:user_id' => 'users#follower_list'
  end

  resources :posts, only: %i[new create index show destroy] do
    resources :photos, only: %i[create]
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :searchs, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true, length: { maximum: 100 }
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    update_attribute(:blocked, true)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :caption, presence: true, length: { maximum: 100 }
  has_one_attached :avatar
  has_many_attached :images
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  acts_as_taggable

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :name, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :searchs

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  validates :name, presence: true, length: { maximum: 50 }
  validates :username, presence: true, length: { maximum: 50 } 
  validates :password, presence: true, length: { maximum: 50 }

  has_one_attached :avatar

  acts_as_followable
  acts_as_follower

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def self.guest
    find_or_create_by(email: 'guest@example.com') do |user|
      user.password = 'password'
    end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(name: data['name'], email: data['email'], password: Devise.friendly_token[0, 20])
    user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    respond_to :js if @like.save
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    respond_to :js if @like.destroy
  end

  private

  def like_params
    params.permit(:post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show destroy]

  def new
    @post = Post.new
    @user = User.find_by(id: params[:user_id])
  end

  def create
    @post = Post.new(post_params)
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    if @post.save
      flash[:notice] = '投稿が保存されました'
      redirect_to root_path
    else
      flash[:alert] = '投稿に失敗しました'
      redirect_to root_path
    end
  end

  def index
    @posts = Post.all.order('created_at DESC')
    @posts = Post.tagged_with(params[:tag_name].to_s) if params[:tag_name]
  end

  def show; end

  def destroy
    if @post.user == current_user
      flash[:notice] = '投稿が削除されました' if @post.destroy
    else
      flash[:alert] = '投稿の削除に失敗しました'
    end
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:caption, :tag_list, :youtube_url, :address, images: []).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
    @posts = Post.includes(:user).where(posts: { user_id: params[:id] }).order('created_at DESC')
  end

  def follow
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    redirect_to user_path(@user)
  end

  def unfollow
    @user = User.find(params[:user_id])
    current_user.stop_following(@user)
    redirect_to user_path(@user)
  end

  def follow_list
    @user = User.find(params[:user_id])
  end

  def follower_list
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?

    gravatar_id = Digest::MD5.hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>tripalbum</title>
    <%= csrf_meta_tags %>
    <%= display_meta_tags site: 'tripalbum' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Flamenco" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP" rel="stylesheet" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
  </head>

  <body>
    <div id="wrapper">
      <%= render 'partial/navbar' %> 
      <%= render 'partial/flash' %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render 'partial/footer' %> 
    </div>
    
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
<% end %>

app/views/partial/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
    <div class="light-color post-time no-text-decoration">
      <span><%= time_ago_in_words(comment.created_at).upcase + "前" %></span>
    </div>
  </div>
<% end %>

app/views/partial/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/partial/_follow_form.html.erb
<div id="follow_form">
  <div class="insta_btn2">
    <% if current_user.following? @user %>
      <%= link_to "", {controller: :users,action: :unfollow,user_id: @user.id}, class: "fa fa-handshake-o", method: :put %>
      <p class="follow_me">Forrow me</p>
    <% else %>
      <%= link_to "", {controller: :users,action: :follow,user_id: @user.id}, class: "fa fa-handshake-o", method: :put %>
      <p class="follow_me">Unforrow me</p>
    <% end %>
  </div>
</div>

app/views/partial/_footer.html.erb
<div class="footerbar">
  <div class="copyright">
    <p class="copyright-word">Copyright © 2020 tripalbumapp. All Rights Reserved.</p>
  </div>
</div>

app/views/partial/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/partial/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
    <div class="row">
      <ul class="navbar-nav ml-md-auto align-items-center">
        <div class="row">
          <% unless user_signed_in? %>
            <% if current_page?(root_path) %>
              <li>
                <%= link_to "サインイン", sign_in_path, class: "btn btn-primary commonNavBtn btn-sm" %>
              </li>
              <li>
                <%= link_to "サインアップ", new_user_registration_path, class: "btn btn-success commonNavBtn btn-sm" %>
              </li>
            <% end %>
          <% end %>

          <% if user_signed_in? %>
            <li>
              <%= link_to "投稿", new_post_path, class: "btn btn-primary btn-push" %>
            </li>
            <% unless current_page?(current_user) %>
              <li>
                <%= link_to "", user_path(current_user), class: "nav-link commonNavIcon profile-icon" %>
              </li>
            <% end %> 
            <% unless current_page?(root_path) %>
              <li>
                <%= link_to "", root_path, class: "nav-link commonNavIcon home-icon" %>
              </li>
            <% end %>
            <% if @user == current_user %>
              <li>
                <button type="button" class="nav-link commonNavIcon setting" data-toggle="modal" data-target="#exampleModal"></button>
              </li>
            <% end %>
            <% unless current_page?(searchs_path) %>
              <li>
                <%= link_to "", searchs_path, class: "nav-link commonNavIcon search-icon" %>
              </li>
            <% end %>
          <% end %>
        </div>
      </ul>
    </div>
  </div>
</div>